### ISSUE TITLE
第一次用没问题，第二次用开始这个停不下来了

### ISSUE THREAD

**Issue by jackoelv** [moonshawdo/checkgoogleip#13]
一直在扫描，我看ip_tmpok.txt里面的ip数都好几千了，还在继续搜IP，扫了几个下午都没停下来，这是个啥问题？

**Comment by moonshawdo** [comment]
之前ip_tmpok.txt是所有可以连接成功的IP，里面有gae可用与不可用的IP，新的代码会区分到不同的文件，其中 ip_tmpok.txt是只保存gae可用的IP列表，但是最后几行，如果发现有NA_的IP，表示曾经成功过，但是最近检查失败。

**Comment by haitaowu** [comment]
谁有解决办法怎么让它停下来，我是在mac上跑的

**Comment by moonshawdo** [comment]
新版本应该修复了这个问题，在win与unbuntu都试过可以用ctrl+c停止。
