### ISSUE TITLE
想增加扫描结果数目

### ISSUE THREAD

**Issue by somebird** [moonshawdo/checkgoogleip#15]
运行批命令，每次只扫出来50个结果，如果我想让它每次扫出300个，怎么样能办到？

**Comment by yfdyh000** [comment]
checkip.py 中 g_maxhandleipcnt = 50 改成 g_maxhandleipcnt = 300

**Comment by somebird** [comment]
感谢回答！

**Comment by Firef0x** [comment]
@yfdyh000 您好！

这样增大结果数会不会造成路由器短暂断流呀？

此致！

**Comment by yfdyh000** [comment]
@Firef0x 不会，这个是决定得到多少时自动停止的参数。如果断流，应调低的是 g_maxthreads = 90。

**Comment by moonshawdo** [comment]
可以按 @yfdyh000 所说修改g_maxhandleipcnt，扫描时间会增加
