### ISSUE TITLE
一个修改版本的功能建议采用

### ISSUE THREAD

**Issue by CNMan** [moonshawdo/checkgoogleip#16]
https://code.google.com/p/goagent/issues/detail?id=19050
修改内容：
1、可设置参数提前，方便修改。
2、输出中文化。
3、增加 ip_tmpnot 区分非 google IP。
4、清空内置 IP 库，使用外挂 eip.txt 自定义 IP。
5、去除 IP 输出最后一个“|”。
使用方法：
下载 checkip.bat、checkip.py、eip.txt 放入 goagent 目录，运行 checkip.bat，结果输出到 ip.txt，请自行粘贴到配置文件。

IP 库放在一个文件中这个功能是否能够合并进来？
另外，能否自动整理ip_tmpok.txt，删除相同的IP，只保留最后一次的记录？

**Comment by lenovo-me** [comment]
在VPS（debian 7 x64）上运行tmpno和tmpok是连续打印，不换行？
本地windows上正常

**Comment by mhohai** [comment]
@lenovo-me 你是不是将Linux下生成的文本文件拿到Windows下看不换行？（是就对了`\n\r`）

**Comment by lenovo-me** [comment]
@mhohai 是的，下载到windows看的，有什么办法让换行吗？

**Comment by Firef0x** [comment]
@lenovo-me ，您好！

不要用记事本打开，用代码编辑器打开（如 `Notepad2` `Notepad++` `UltraEdit` 等），一般就能自动识别 `Linux` 换行符。

此致！:bow:

**Comment by lenovo-me** [comment]
@Firef0x 我用的EditPlus，一会去试试别的
