### ISSUE TITLE
做了一个集成ip自动搜索的GoAgent

### ISSUE THREAD

**Issue by xxnet** [moonshawdo/checkgoogleip#17]
做了一个集成ip自动搜索的GoAgent，方便使用:
https://github.com/XX-net/XX-Net

**Comment by Firef0x** [comment]
这……Go阿根廷有发过 `3.1.30` 版吗？ :sweat_smile: 
[XX-Net/goagent/3.1.30 · XX-net/XX-Net](https://github.com/XX-net/XX-Net/tree/master/goagent/3.1.30)

**Comment by gdgoldlion** [comment]
。。。阿根廷不是这么拼

**Comment by luieswww** [comment]
youtube video can not open , test just now, good config WEB UI ,good job

**Comment by xxnet** [comment]
3.2 版本的代码太乱了，看不懂，因此fork 3.1.x的版本.
也许该叫XX-Agent ：-(
