### ISSUE TITLE
CPU占用高的问题貌似没解决？

### ISSUE THREAD

**Issue by CNMan** [moonshawdo/checkgoogleip#19]
越来越高，看着都恐怖:)
[Imgur](http://i.imgur.com/XhUBQoQ.png)

**Comment by LGA1150** [comment]
我设置线程数为900
i7-3770K占用50%
（实际上已经满了，因为超线程）

**Comment by moonshawdo** [comment]
这个问题我一直都没有遇到，请问你们是使用外部ip列表来测试的吗？IP数大概有多少？
