### ISSUE TITLE
新版本的默认检查可用IP数设置项不起作用了

### ISSUE THREAD

**Issue by somebird** [moonshawdo/checkgoogleip#25]
IP不停地扫下去，那个设置不起作用了，我设g_maxhandleipcnt = 10或者设置为g_maxhandleipcnt = 200，都不起作用，程序无法停止，直到我按CTR+C

**Comment by moonshawdo** [comment]
当g_maxhandleipcnt设置10时，ctrl+c后显示有多少IP符合扫描要求的？或者说ip.txt里面的ip有多少个?

**Comment by somebird** [comment]
有30多个

**Comment by qidanei624** [comment]
非常感谢作者，很棒！！ 学习了！

**Comment by somebird** [comment]
我弄错了，不好意思，ip_tmpok.txt里面30来个，ip.txt里面只有两个，扫了一两个小时，现在成功率巨低。
