### ISSUE TITLE
部分IP证书貌似校验不对

### ISSUE THREAD

**Issue by CNMan** [moonshawdo/checkgoogleip#26]
69.13.199.94 3116 www.google.com gws
64.15.119.139 6093 www.google.com gws
64.15.126.213 7603 www.google.com gws

但浏览器给的警告不是google的
![Image of firefox](http://i.imgur.com/aA3hmhn.png)

**Comment by yfdyh000** [comment]
https://69.13.199.94 我这里连不上，其他两个IP都是 www.google.com 的证书。

结果是什么时候的，以前的吧。因为是在ISP部署的GGC，IP所属服务器可能会变化。重扫一遍就行。

**Comment by CNMan** [comment]
刚结束的，挨个在浏览器看了下证书，后面2个刚还不是google的，现在又是了...
试了几十个，只有www.google.com的有问题，google.com和*.google.com没出现错的
