### ISSUE TITLE
导入自定义的IP不能扫完

### ISSUE THREAD

**Issue by ncmon** [moonshawdo/checkgoogleip#27]
我把线程改成900，自定义IP0/16的6万5个IP扫完要8分钟左右，但是导入600多万个IP只要50分钟就扫完了，我已经把最大可用IP数量g_maxhandleipcnt改成1千万了还是没用，扫了50分钟就停住了窗口2分钟没动请问该怎么解决呢

**Comment by blob2015** [comment]
ip_tmperror有多大……你扫过的ip，都有记录，会自动略过……

**Comment by ncmon** [comment]
我测试前把那3个记录都删了在去扫的还是一样
