### ISSUE TITLE
含gws的域名也被放进ip_tmpok.txt里了

### ISSUE THREAD

**Issue by CNMan** [moonshawdo/checkgoogleip#28]
61.113.12.26 1031 gwsrv.ticstage.co.jp 
108.59.50.82 1391 magik.trngws.dcs.in.gov 
122.248.245.155 578 *.ciggws.net 
122.248.247.89 1188 *.ciggws.net 
160.96.2.63 1985 internet-stg.gwsx.gov.sg 
160.96.2.67 1797 www.gwsx.gov.sg 
175.41.131.13 531 *.ciggws.net 
175.41.133.26 500 *.ciggws.net 
175.41.140.160 750 *.ciggws.net 
175.41.140.254 563 *.ciggws.net 
175.41.146.34 781 *.ciggws.net 
192.200.179.40 1063 www.gwsupplyco.com 
203.116.15.206 484 secure1.cgwstage.com 
203.116.82.37 563 vpngwsgems.mindef.gov.sg 
212.113.20.244 2344 gentingws.acteol.co.uk 
219.117.205.118 704 rdgws.iwink.jp

**Comment by moonshawdo** [comment]
这么奇怪，我用你这些IP去测试，结果都可以正确地放在ip_tmpno.txt里面  
    
    E:\thirdparty\checkgoogleip>python checkip.py
    [Dummy-1]support gevent
    [Dummy-1]load last result,ok cnt:6160,ok file line:1935,error cnt: 48287
    [Thread-2]begin to get ramdom ip
    [Thread-2]load extra ip ok,line:16,load default ip: 0
    [Thread-2]ramdom ip thread stopped.had check ip: 0,rest ip queue size: 16
    [Dummy-1]need create max threads count: 128
    [Thread-13]ip: 175.41.146.34,CN: *.ciggws.net,O:CANON INC.,svr: ,not gae
    [Thread-12]ip: 175.41.140.254,CN: *.ciggws.net,O:CANON INC.,svr: ,not gae
    [Thread-11]ip: 175.41.140.160,CN: *.ciggws.net,O:CANON INC.,svr: ,not gae
    [Thread-10]ip: 175.41.133.26,CN: *.ciggws.net,O:CANON INC.,svr: ,not gae
    [Thread-9]ip: 175.41.131.13,CN: *.ciggws.net,O:CANON INC.,svr: ,not gae
    [Thread-6]ip: 122.248.247.89,CN: *.ciggws.net,O:CANON INC.,svr: ,not gae
    [Thread-16]ip: 203.116.82.37,CN: vpngwsgems.mindef.gov.sg,O:Ministry Of Defence,svr: ,not     gae
    [Thread-15]ip: 203.116.15.206,CN: secure1.cgwstage.com,O:,svr: ,not gae
    [Thread-14]ip: 192.200.179.40,CN: www.gwsupplyco.com,O:,svr: ,not gae
    [Thread-5]ip: 122.248.245.155,CN: *.ciggws.net,O:CANON INC.,svr: ,not gae
    [Thread-4]ip: 108.59.50.82,CN: magik.trngws.dcs.in.gov,O:State of Indiana,svr: ,not gae
    [Thread-3]ip: 61.113.12.26,CN: gwsrv.ticstage.co.jp,O:,svr: ,not gae
    [Thread-17]ip: 212.113.20.244,CN: gentingws.acteol.co.uk,O:,svr: ,not gae
    [Thread-8]ip: 160.96.2.67,CN: www.gwsx.gov.sg,O:Infocomm Development Authority of     Singapore,svr: ,not gae
    [Thread-7]ip: 160.96.2.63,CN: internet-stg.gwsx.gov.sg,O:Infocomm Development Authority of Singapore,svr: ,not gae
    [Thread-18]ip: 219.117.205.118,CN: rdgws.iwink.jp,O:,svr: ,not gae
    [Dummy-1]try to collect ssl result,check ip cnt: 16,times:5s
    [Dummy-1]write to file ip.txt ok,count:0
    [Dummy-1]file ip_tmpok.txt no need sort

或者看一下你现在使用的版本是哪个commit的，很久之前的确都是放在ip_tmpok里面，不过后期修改过的了，非gae ip单独放到ip_tmpno.txt里面。

**Comment by CNMan** [comment]
不好意思，是我的锅，整理去重复IP的批处理把含gws的都放到ip_tmpok.txt里了
