### ISSUE TITLE
gvs ip如今能用于goagent，求更新

### ISSUE THREAD

**Issue by fuckGFW2015** [moonshawdo/checkgoogleip#33]
gvs ip扫出来后，一个个复制进去goagent配置文件很不方便

**Comment by blob2015** [comment]
GVS可以用了？

**Comment by Mybestway** [comment]
自己改，这里https://github.com/moonshawdo/checkgoogleip/pull/32/files

**Comment by blob2015** [comment]
感谢楼上Mybestway
