### ISSUE TITLE
新版本 搜出的 ip 不可用

### ISSUE THREAD

**Issue by kuchaguangjie** [moonshawdo/checkgoogleip#34]
新版本的大部分ip都提示 404 / 405 错误,

回滚到以下 版本就好了:

git checkout a7f497253d12c825b2ab5f82a318fdc631e1a956

具体为什么, 请作者查下.

**Comment by moonshawdo** [comment]
最新版本因为需要搜索gvs的IP，需要配合最新版本的goagent来使用，如果你用的goagen不是最新的，可以用 a25066d91ead1d9d67a7e221e1f634d14f86cd73 或 a7f497253d12c825b2ab5f82a318fdc631e1a956

**Comment by kuchaguangjie** [comment]
我的 goagent 是 3.2.3, 好像就是最后一个版本, 虽然 github 上的 goagent 有代码更新, 但是 并没有 发布版本噢.

另外, 建议 作者在发布 checkgoogleip 的时候, 可以加上 tag, 这样方便 用户知道自己的版本, 也方便 回滚.

**Comment by lvniqi** [comment]
@kuchaguangjie 就是需要更新那更新的一部分代码....

**Comment by kuchaguangjie** [comment]
@lvniqi ok, 了解, 我还是等 goagent 发布新版本再升级, 现在的 goagent 3.2.3 和 checkgoogleip a7f4972 用起来 没什么问题, 速度相当快.

**Comment by kuchaguangjie** [comment]
刚升级 goagent 到 最后提交的代码 985cbd5 (> 3.2.3), 然后用 最新的 checkgoogleip 7d090ee, 发现搜ip 非常快, 比原来有效多了! 多谢!
