### ISSUE TITLE
最近扫出来的IP提示ok但是并不能正常使用

### ISSUE THREAD

**Issue by Lavande** [moonshawdo/checkgoogleip#36]
扫描很快，一会儿就出来一堆可用的地址，放进去之后goagent也说是good ip，但是打开网页时提示：

> The request method POST is inappropriate for the URL /_gh/. That’s all we know

是不是在判断ip是否可用时还要加一些条件？

**Comment by moonshawdo** [comment]
一般出现这种情况，是因为你使用的gogaent版本没有支持gvs的IP，有两种解决方法
1.  到gogagent的github下载最新的代码
2.  下载只支持扫描gws ip版本： https://github.com/moonshawdo/checkgoogleip/releases/tag/gws

**Comment by Lavande** [comment]
因为是最新版3.2.3，我用了方法2，现在正常了！
不过扫了好久啊，大概扫了七八个小时，最后扫了11个出来，好在都能用，谢谢！
