### ISSUE TITLE
添加IPV6地址检测

### ISSUE THREAD

**Issue by wugh** [moonshawdo/checkgoogleip#5]
能不能添加IPV6地址检测呢？

**Comment by blob2015** [comment]
期待ipv6

**Comment by wugh** [comment]
不知道有没有办法获取到google的ipv6网段，我都是通过ping来获取网段，然后获取里面的一些ip，目前写了个脚本，自己用着没问题，你可以尝试尝试，只能在linux下用哦
https://gist.github.com/wugh/5ed0f4d7bf98a3741409

**Comment by CNMan** [comment]
@wugh http://bgp.he.net/AS15169#_prefixes6
其他AS类似
AS15169
AS36384
AS16591
AS41264
AS36492
AS22577
AS24424
AS36040
AS19448
AS22859
AS36039
AS36385
AS45566
AS36987

NSLOOKUP也能获取一些：
```
C:\Windows\system32>nslookup -q=TXT _netblocks2.google.com 8.8.8.8
服务器:  google-public-dns-a.google.com
Address:  8.8.8.8

非权威应答:
_netblocks2.google.com  text =

        "v=spf1 ip6:2001:4860:4000::/36 ip6:2404:6800:4000::/36 ip6:2607:f8b0:4000::/36 ip6:2800:3f0:4000::/36 ip6:2a00:1450:4000::/36 ip6:2c0f:fb50:4000::/36 ~all"

C:\Windows\system32>nslookup -q=TXT _netblocks2.google.com 8.8.4.4
服务器:  google-public-dns-b.google.com
Address:  8.8.4.4

非权威应答:
_netblocks2.google.com  text =

        "v=spf1 ip6:2001:4860:4000::/36 ip6:2404:6800:4000::/36 ip6:2607:f8b0:4000::/36 ip6:2800:3f0:4000::/36 ip6:2a00:1450:4000::/36 ip6:2c0f:fb50:4000::/36 ~all"
```

**Comment by wugh** [comment]
@CNMan 我当时也去查询这个netblocks里面的IP，但是这个range非常大，而且好多都无法ping通，是不是因为虽然google有这么多v6的IP网段，但是很多都没有启用呢？

**Comment by CNMan** [comment]
@wugh 所以v6是不是该换个思路了？整个IP段check不是好办法
感觉 https://github.com/lennylxx/ipv6-hosts 这个项目的思路不错，找出domain规律，再check dns返回的结果
